### ISSUE TITLE
Standardise unit metric and design the goal system

### ISSUE THREAD

**Issue by fischsux** [FitMi/FitMi-iOS#1]
统一度量衡
1. Speed
2. Endurance
3. Agility

Find out the formula for exercise goal. （达成目标，未达成目标）
What we have:
1. Current value
2. Goal
3. Mood

**Comment by lozy219** [comment]
1. 统一度量衡，统一文字，统一货币；
2. 废除分封制，设立郡县；
3. 焚书坑儒。

**Comment by Gisonrg** [comment]
@lozy219 💩

**Comment by HuangBohan** [comment]
Strength: Last 3 days steps (10 point / 1000 steps)

Stamina: Last 3 days distance (10 point / 1000 meters)

Agility: Last 3 days flights (5 point / 1 floor) ( 闪避几率 = A1 / [2 \* (A1 + A2)] )

Critical chance: mood percentage / 5

HP: Last 7 days (Strength + Stamina + Agility) / 2 + Level

XP / Level
- You receive 4.00 XP for each second you are active the exercise
- You will receive a bonus 250 XP reward upon finishing 1 goal

Goals
- Steps goal = 2000 + 1000 \* X
- Distance goal = 1000 + 500 \* X
- Flights goal = 5 + 5 \* X

Level   XP Needed to Level Up
1       1500
2       3000
3       4500
4       6000
5       7500
6       8500
7       9500
8       10500
9       11500
10      12500
11      13500
12      14500
13      15500
14      16500
15      17500
16      18500
17      19000
18      19500
19      20000
20      20500
21      21000
22      21500
23+     22000

Combat: Rock–paper–scissors (play against random number generator)
