### ISSUE TITLE
Changing timer bar background?

### ISSUE THREAD

**Issue by lozy219** [FitMi/FitMi-iOS#25]
Now it's very hard to distinguish the timer/health bar's background and the actual view background. I definitely have no idea when is my timer bar full. Interestingly the cheating AI can hit me exactly at the moment when his timer is full, that's unfair! 😠 

![image](https://cloud.githubusercontent.com/assets/6064797/19618633/a3cc844e-9882-11e6-9b96-6d17fcad2094.png)

**Comment by Gisonrg** [comment]
@null09264 
Refer to this, can we add icon (like ❤️  and ⏲ ) next to those bar?
